# Generated by Django 5.1 on 2024-08-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolatilityChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('time', models.TimeField(blank=True, db_column='Time', null=True)),
                ('open', models.DecimalField(blank=True, db_column='Open', decimal_places=4, max_digits=10, null=True)),
                ('high', models.DecimalField(blank=True, db_column='High', decimal_places=4, max_digits=10, null=True)),
                ('low', models.DecimalField(blank=True, db_column='Low', decimal_places=4, max_digits=10, null=True)),
                ('close', models.DecimalField(blank=True, db_column='Close', decimal_places=4, max_digits=10, null=True)),
                ('indicator1_on_chart', models.DecimalField(blank=True, db_column='Indicator1_OnChart', decimal_places=4, max_digits=10, null=True)),
                ('indicator2_on_chart', models.DecimalField(blank=True, db_column='Indicator2_OnChart', decimal_places=4, max_digits=10, null=True)),
                ('indicator1_in_pane_below', models.DecimalField(blank=True, db_column='Indicator1_InPaneBelow', decimal_places=3, max_digits=10, null=True)),
                ('symbol', models.CharField(blank=True, db_column='SYMBOL', max_length=100, null=True)),
            ],
        ),
    ]
